// Categorías de habitaciones de Ostende — usadas en la home y en /ostende/habitaciones.
export const CATEGORIES = [
  {
    href: '/ostende/categoria-superior',
    src: '/img/ostende/home/habitacion-superior.webp',
    alt: 'Categoría Superior',
    title: 'Categoría Superior',
    size: '28-30 m²',
    capacity: '2 a 3 personas',
    view: 'Vista al mar',
    description: 'Amplia vista franca e imponente al mar, camas King size y un completo baño con bañera.',
  },
  {
    href: '/ostende/categoria-ejecutiva',
    src: '/img/ostende/habitaciones2/piso4/p407.jpg',
    alt: 'Categoría Ejecutiva',
    title: 'Categoría Ejecutiva',
    size: '20 m²',
    capacity: '2 a 3 personas',
    view: 'Vista al mar',
    description: 'Fabulosa vista al mar, camas King size o Twins y baño con bañera.',
  },
  {
    href: '/ostende/categoria-standard',
    src: '/img/ostende/home/habitacion-estandar.webp',
    alt: 'Categoría Estandar',
    title: 'Categoría Estándar',
    size: '20 m²',
    capacity: '2 a 3 personas',
    description: 'Camas Queen size y baño con ducha, todo lo necesario para tu estadía.',
  },
  {
    href: '/ostende/categoria-familiar',
    src: '/img/ostende/categoria-familiar/familiar-1.webp',
    alt: 'Categoría Familiar',
    title: 'Categoría Familiar',
    capacity: '4 a 5 personas',
    description: 'Departamentos con 2 baños y habitación cuádruple con 1 baño, ideal para viajar en familia.',
  },
];
